# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefiles                                          :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rfork <marvin@42.fr>                       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/08/15 14:37:15 by rfork             #+#    #+#              #
#    Updated: 2019/08/15 16:24:37 by rfork            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
SRCS = ft_display_file.c

all: $(NAME)

$(NAME):
	    gcc -Wall -Wextra -Werror -o $(NAME) $(SRCS)
		 
clean:
		rm $(NAME)

fclean: clean

re: fclean all
